# Project 9 - Working with OLS

Having built statistics functions, we are now ready to build a function for regression analysis. We will start by building the an regression. We will use linear algebra to estimate parameters that minimize the sum of the squared errors. This is an ordinary least squares regression. 

An OLS regression with one exogenous variable takes the form. 

$y = \alpha + \beta_1x_1 + \mu $

$\beta_0 = \alpha + \mu$

We merge the error term, which represents bias in the data, with alpha to yield the constant, $\beta_0$. This is necessary since OLS assumes an unbiased estimator where:

$\sum_{i=0}^{n-1} e_{i}=0$

Each estimate of a point created from a particular observation takes the form.

$y_i = \beta_0 + \beta_1x_{1,i} + e_i$

This can be generalized to include k exogenous variables:

$y_i = \beta_0 + (\sum_{j=1}^{k} \beta_jx_{i,j}) + e_i$

Ideally, we want to form a prediction where, on average, the right-hand side of the equation  yields the correct value on the left-hand side. When we perform an OLS regression, we form a predictor that minimizes the sum of the distance between each predicted value and the observed value drawn from the data. For example, if the prediction for a particular value of y is 8, and the actual value is 10, the error of the prediction is -2 and the squared error is 4.

To find the function that minimizes the sum squared errors, we will use matrix algebra, also known as linear algebra. For those unfamiliar, the next section uses the numpy library to perform matrix operations. For clarity, we will review the linear algebra functions that we will use with simple examples.

## Linear Algebra for OLS

We solve the following function for a vector of beta values ($\beta$), constants whose values represent estimates of the effect of variables in the set **_X_** on the selected endogenously generate variable $y$. The matrix **_X_** also includes a vector of ones used to estimate the constant $\beta_0$.

$\beta = (X'X)^{-1}X'Y$

$Y =$ Observations for Endogenous Variable

$X =$ Observations for Exogenous Variables

$X' =$ $X$-transpose

$(X'X)^{-1} =$ Inverse of $X'X$

### Inverting a Matrix

In reviewing the linear equation for estimating $\beta$, we confront two unique operations worth understanding. Included in these are some key concepts in linear algebra, including the identity matrix $I$ and linear independence. The best way to understand these concepts is by working with some sample vectors. Consider the matrix $X$ consisting of vectors $x_0$,$x_1$,…,$x_{n-1}$,$x_n$. We must check that these vectors are linearly independent. We do this by joining $X$ with an identity matrix and thus create:

$A = [XI]$

We transform this to show that the product of $A$ and $X^{-1}$ is equal to the product of and an identity matrix, $I$ and $X^{-1}$

$AX^{-1} = [XI]X^{-1}$

$AX^{-1} = [IX^{-1}]$

Let us solve for $AX^{-1}$ using the following vectors for $X$. 

$\begin{equation*}
X = \begin{bmatrix}
1 & 2 & 1 \\
4 & 1 & 5 \\
6 & 8 & 6
\end{bmatrix}
\end{equation*}$

Concatenate a 3 X 3 identity matrix on the left of $X$:

$\begin{equation*}
I = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\end{equation*}$

$\begin{equation*}
[XI] = \begin{bmatrix}
1 & 2 & 1 & 1 & 0 & 0 \\
4 & 1 & 5 & 0 & 1 & 0 \\
6 & 8 & 6 & 0 & 0 & 1
\end{bmatrix}
\end{equation*}$

If we perform row operations on $A$ to transform $X$ in $[XI]$ into $I$, then we $I$ will be transformed into $X^{-1}$:

$\begin{equation*}
[XI] = \begin{bmatrix}
1 & 2 & 1 & 1 & 0 & 0 \\
4 & 1 & 5 & 0 & 1 & 0 \\
6 & 8 & 6 & 0 & 0 & 1
\end{bmatrix}
\end{equation*}$




$\begin{equation*}
r_2 - 4r_1:\begin{bmatrix}
1 & 2 & 1 & 1 & 0 & 0 \\
0 & -7 & 1 & -4 & 1 & 0 \\
6 & 8 & 6 & 0 & 0 & 1
\end{bmatrix}
\end{equation*}$


$\begin{equation*}
r_3 - 6r_1:\begin{bmatrix}
1 & 2 & 1 & 1 & 0 & 0 \\
0 & -7 & 1 & -4 & 1 & 0 \\
0 & -4 & 0 & -6 & 0 & 1
\end{bmatrix}
\end{equation*}$


$\begin{equation*}
r_2 \leftrightarrow r_3:\begin{bmatrix}
1 & 2 & 1 & 1 & 0 & 0 \\
0 & -4 & 0 & -6 & 0 & 1\\
0 & -7 & 1 & -4 & 1 & 0 
\end{bmatrix}
\end{equation*}$

$\begin{equation*}
r_2/{-4}:\begin{bmatrix}
1 & 2 & 1 & 1 & 0 & 0 \\
0 & 1 & 0 & 3/2 & 0 & -1/4\\
0 & -7 & 1 & -4 & 1 & 0 
\end{bmatrix}
\end{equation*}$

$\begin{equation*}
r_3 + 7r_2:\begin{bmatrix}
1 & 2 & 1 & 1 & 0 & 0 \\
0 & 1 & 0 & 3/2 & 0 & -1/4\\
0 & 0 & 1 & 13/2 & 1 & -7/4 
\end{bmatrix}
\end{equation*}$

$\begin{equation*}
r_1 + -2r_2 - r_3:\begin{bmatrix}
1 & 0 & 0 & -17/2 & -1 & 9/4 \\
0 & 1 & 0 & 3/2 & 0 & -1/4\\
0 & 0 & 1 & 13/2 & 1 & -7/4 
\end{bmatrix}
\end{equation*}$

$\begin{equation*}
IX^{-1}=\begin{bmatrix}
1 & 0 & 0 & -8.5 & -1 & 2.25 \\
0 & 1 & 0 & 1.5 & 0 & -0.25\\
0 & 0 & 1 & 6.5 & 1 & -1.75 
\end{bmatrix}
\end{equation*}$

$\begin{equation*}
X^{-1}=\begin{bmatrix}
-8.5 & -1 & 2.25 \\
1.5 & 0 & -0.25\\
6.5 & 1 & -1.75 
\end{bmatrix}
\end{equation*}$

By transforming $X$ in matrix $XI$ into an identity matrix, we transform the $I$ matrix into $X^{-1}$. This also confirms that the vectors comprising X are independent, meaning that one vector in the set comprising $X$ cannot be formed from the combination and or transformation of the others. A fundamental assumption of regression analysis is that data generated from factors believed to determine the y-values are independent of one another.

### Linear Algebra in _numpy_

We can check this using linear algebra functions in numpy. We start by creating numpy arrays that we will transform into vectors in the second step. 

In [1]:
import numpy as np

# create basis for matrix in np.array
x1 = np.array([1,2,1])
x2 = np.array([4,1,5])
x3 = np.array([6,8,6])
print(x1,x2,x3, sep = "\n")

[1 2 1]
[4 1 5]
[6 8 6]
[1 2 1]
[4 1 5]
[6 8 6]


In [2]:
# convert np.arrays to np.matrix values. 
x1 = np.matrix(x1)
x2 = np.matrix(x2)
x3 = np.matrix(x3)
print(x1,x2,x3, sep = "\n")

[[1 2 1]]
[[4 1 5]]
[[6 8 6]]
[[1 2 1]]
[[4 1 5]]
[[6 8 6]]


In [ ]:
# Combine the separate matrix values into one matrix
X = np.concatenate((x1,x2,x3))
X

In [ ]:
# to create an inverse matrix, we can just use X.getI(). This allows us to bypass the algebra
X_inverse = X.getI()
X_inverse

In [ ]:
# to round out this number that was supposed to be zero, we use np.round
np.round(X_inverse, 2)

In [ ]:
# Swaps i and j rows. Allows for transposition of data if it is unorganized or in a 
# difficult position. This allows for better computation
X_transpose = X.getT()
X_transpose

## Regression Function

Now that we have learned the necessary operations, we can understand the operations of the regression function. If you would like to build your own regression module, reconstruct the scripts form Chapter 7. In this lesson, we will use the statsmodels OLS method to reconstruct and compare statistics from an OLS regression. 

Recall that we estimate the vector of beta parameters for each variable with the equation:

$\beta = (X'X)^{-1}X'Y$

Each estimated $\beta$ value is multiplied by each observation of the relevant exogenous variable estimate the effect of the value on the endogenous, $Y$, value.

We will run a regression In order to estimate the parameters, we will need to import data, define the dependent variable and independent variables, and transform these into matrix objects. 

Let's use the data from chapter 6 with the addition real GDP per capita. This combined set of data is saved in the repository as a file created in chapter 8.

In [ ]:
# We now can use this linear algebra to calculate the betas in our regression. 

# Now we will import data and run a regression

In [ ]:
import pandas as pd
import statsmodels.api as sm

# download madison economic data from the source document. This GDP data goes back far
# to virtually the beginning of recorded economics
mgdp = pd.read_excel(
    "https://www.rug.nl/ggdc/historicaldevelopment/maddison/data/mpd2020.xlsx",
                    index_col = [0,2],
                    parse_dates = True,
                    sheet_name = "Full data")
mgdp

In [ ]:
# use the excel file that we downloaded previously on the economic freedom of the world
# 2022 master data. We are planning to incorporate the above data into this EFOTW data

# make sure to parse_dates so that pandas recognizes dates correctly


filename = "efotw-2022-master-index-data-for-researchers-iso.xlsx"
data = pd.read_excel(filename,
                    index_col = [2,0],
                     header = [0],
                     sheet_name = "EFW Panel Data 2022 Report")


data

In [ ]:
# transform names so that they are more easily understandable. We have done this before in 
# previous lessons

rename = {"Panel Data Summary Index": "Summary",
         "Area 1":"Size of Government",
         "Area 2":"Legal System and Property Rights",
         "Area 3":"Sound Money",
         "Area 4":"Freedom to Trade Internationally",
         "Area 5":"Regulation"}

# this will drop all rows with only null values and rename columns based on the above 

data = data.dropna(how="all", axis = 1).rename(columns = rename)
data

In [ ]:
# we now concatenate the mgdp data into the 
data["RGDP Per Capita"] = mgdp["gdppc"]
data

In [ ]:
# delete standard deviation column
del  data["Standard Deviation of the 5 EFW Areas"]

In [ ]:
data

In [ ]:
data.reset_index(inplace = True)
data["Year"] = data["Year"].astype(str).astype("datetime64[ns]").sort_index()
data = data.set_index(["ISO_Code_3", "Year"]).sort_index()
data

In [ ]:
years = np.array(sorted(list(set(data.index.get_level_values("Year")))))
years = pd.date_range(years[0], years[-2], freq = "AS")
countries = sorted(list(set(data.index.get_level_values("ISO_Code_3"))))
index_names = list(data.index.names)
multi_index = pd.MultiIndex.from_product([countries, years[:-1]], names = data.index.names)
data = data.reindex(multi_index)
data

In [ ]:
# we now save this file in an excel file
data.to_excel("EFWAndRGDP.xls")

In [ ]:
# inspect the keys of this file
data.keys()

In [ ]:
# select subset for analysis
data = data[data.keys()[3:]]
data

In [ ]:
# sort data in the by the index columns (previously defined first as iso code second as year)

# it is possible to transform to datetime, but we did not cover it in this lesson. 
# contact Dr. Caton for more assistance

data.sort_index(inplace = True)
data

In [ ]:
reg_vars = list(data.keys())
reg_vars

In [ ]:
# separate columns for analysis. We are using Real GDP per capita as our basis for Y in this analysis

reg_data = data[reg_vars].dropna()
y_var = [reg_vars[-1]]
x_vars = reg_vars[2:-1]
y_var, x_vars

In [ ]:
# already imported statsmodel.api

# set x and y variables as well as add constant
y = reg_data[y_var]
X = reg_data[x_vars]
X["Constant"] = 1
results = sm.OLS(y, X).fit()

# X.values is a matrix

In [ ]:
# create a summary by using results.summary() to view normal regression

results.summary()

In [ ]:
#use predictor to develop a prediction

predictor = results.predict()


# add a column for predicted value based on regression
reg_data[y_var[0] + " Predictor"] = predictor
reg_data

In [ ]:
# Caluculate SSE, SSR, & SST
# SSE = sum square errors, SSR = sum squared from regression, SST = total sum squares


# convert these to name[0] for this next analysis. Make sure all data has same number of rows.

y_hat = reg_data[y_var[0] + " Predictor"]
y_mean = reg_data[y_var[0]].mean()
y = reg_data[y_var[0]]

In [ ]:
# calculate residuals by subtracting prediction from actual
reg_data["Residuals"] = (y.sub(y_hat))
reg_data["Squared Explained"] = y_hat.sub(y_mean).pow(2)
reg_data["Squared Residuals"] = y.sub(y_hat).pow(2)
reg_data["Squared Totals"] = y.sub(y_mean).pow(2)

reg_data

In [ ]:
# Take sums of columns so we can caluclate the SSR, SSE, and SST

SSR = reg_data["Squared Explained"].sum()
SSE = reg_data["Squared Residuals"].sum()
SST = reg_data["Squared Totals"].sum()
SSR, SSE, SST

# Calculate Estimator Variance 
With the sum of squared errors calculated, the next step is to calculate the estimator variance and use this to construct the covariance matrix. The covariance matrix is used to derive the standard errors and related statistics for each estimated coefficient.

We estimate the variance of the error term of the estimator for the dependent variable. 

$\sigma^2 = \frac{SSE}{n-k}$

$n = $number of observations

$k = $number of independent variables

An increase in the number of exogenous variables tends ot increase the fit of a model. By dividing the $SSE$ by degrees of freedom, $n-k$ , improvements in fit that result from increases in the number of variables are offset in part by a reduction in degrees of freedom. 

Finally, we calculate the covariance matrix, $(X'X)^{-1}$:

$\sigma^2 (X'X)^{-1}$


In [ ]:
# use results tab to retrieve our k and n variables for calculation
# create estimator variance calculation

n = results.nobs
k = len(results.params)
estimator_variance = SSE / (n - k)
n, k, estimator_variance

In [ ]:
# covariance matrix

cov_matrix = results.cov_params()
cov_matrix

In [ ]:
XtX = np.matmul(X.T,X)
XtX

In [ ]:
XtXInv = np.matrix(np.matmul(X.T, X)).getI()
XtXInv

In [ ]:
# calculate covariance matrix by hand (using matrices)
# XtXInv = np.matrix(np.matmul(X.T, X)).getI()

# multiply by estimator_variance
ev_mul_XtXInv = estimator_variance * XtXInv

# transform into pandas dataframe for easy visual 
pd.DataFrame(ev_mul_XtXInv, 
             columns = X.keys(), index = X.keys())



In [ ]:
# now we need to compare these to the other results

results.params

In [ ]:
# show betas and compare to x_vars in covariance matrix

# create our own regression output based on manual computation 
# (same as above pre-made process)

parameters = {}

#print("beta", "\t\t\tSE")
for x_var in X.keys():
    beta_x = results.params[x_var]
    StdErrX = cov_matrix.loc[x_var][x_var]**.5
#    print(beta_x, StdErrX, sep = "\t")
#    print("t:", beta_x / StdErrX)
    parameters[x_var] = {}
    parameters[x_var]["Beta"] = beta_x
    parameters[x_var]["SE"] = StdErrX
    parameters[x_var]["t-stats"] = beta_x / StdErrX
parameters = pd.DataFrame(parameters).T
parameters

 # Calculate $R^2$

The variance term will be used to help us calculate other values. First we estimate the square root of the mean squared error. Since the mean squared error is the variance of the estimator, this means we simply take the square root the variance term

$rootMSE = \sqrt{\sigma^2}$

The square-root of the MSE provides a more readily interpretable estimate of the estimator variance, showing the average distance of predicted values from actual values, corrected for the number of independent variables. 

We also estimate the R2 value. This value indicates the explanator power of the regression

$R^2 = \frac{SSR}{SST}$

This compares the average squared distance between the predicted values and the average value against the average squared distance between observed values and average values. Ordinary least squares regression minimizes the squared distance between the predicted value and the average value. If values are perfectly predicted, then the SSR would equal the SST. Usually, the SSR is less than the SST. It will never be greater than the SST.


In [ ]:
# calculate rsquared
r2 = SSR / SST
r2

### Adjusted R-Squared
Although the $R^2$ is a useful measure to understand the quality of the explanation provided by the selected exogenous variables. Recall that:

$R^2 = \frac{SSR}{SST}$


Notice that as the degrees of freedom decrease, the numerator necessarily decreases as well. One should not depend solely on the adjusted $R^2$ to consider the strength of a regression's results, but it is often useful to help gauge whether or not a marginal addition of a variable improves explanatory power of a regression.

${R^2}_{Adjusted} = 1 - \frac{\frac{SSE}{n - k}}{\frac{SST}{n-1}}$


In [ ]:
# as the number of explanitory variables increases, the adjusted r2 reduces in value

r2_adjusted = 1 - (SSE / (n - k)) / (SST / (n - 1))
r2_adjusted

# Check the distribution of residuals

In [ ]:
import matplotlib.pyplot as plt
plt.rcParams.update({"font.size":26})
fig, ax = plt.subplots(figsize = (12,8))
reg_data[["Residuals"]].plot.hist(bins = 100, ax = ax)
plt.xticks(rotation=90)

### thinking through unit-root and Cointegration problems

In [ ]:
# plot the real GDP per capita vs our economic freedom

# difference graph showed below of five year differences

# data bias present since recent data is more easily found,
# old data appears more intermittently, so inherit bias is found here

plot_df = data.loc["USA"][x_vars + y_var]
fig, ax = plt.subplots(figsize = (24,12))
plot_df.diff(5).dropna().plot.line(ax = ax, secondary_y = y_var, legend = True)

In [ ]:
# using log difference helps to push assumptions towards a normalized 
# distribution. Below it shows this distribution with few outliers

np.log(data[y_var]).diff(5).plot.hist(bins = 10)

### Warning: having more recent data biases estimates toward present inferences from present data

In [ ]:
## Regressions with Logged Differences
years_diff = 5
reg_data = data
# take the log of real gdp then group by difference
reg_data["RGDP Per Capita"] = np.log(data["RGDP Per Capita"]).groupby(
    "ISO_Code_3").diff(years_diff)

# replace infinite values with null values since it will cause issues
reg_data = reg_data.replace([np.inf, -np.inf], np.nan)
reg_data.loc["USA"]


In [ ]:
r_df = reg_data.dropna(axis = 0, how = "any")
y = r_df[y_var]
X = r_df[x_vars]
X["Constant"] = 1
results = sm.OLS(y, X).fit()
r_df["Predictor"] = results.predict()
r_df["Residuals"] = results.resid
results.summary()

In [ ]:
r_df

In [ ]:
# plot the residuals from the above. 
# This looks reasonable for a normal distribution

fig, ax = plt.subplots(figsize = (12,8))
r_df[["Residuals"]].plot.hist(bins = 100, ax = ax)

# vertical line plot of mean of residuals
ax.axvline(r_df["Residuals"].mean(), ls = "--", linewidth = 5, color  = "k")

In [ ]:
# create dictionary with results
results_dict = {"Beta":results.params,
               "t-stats": results.tvalues,
               "p-values": results.pvalues,
               "SE": results.bse}



results_df = pd.DataFrame(results_dict).round(3)
results_df.to_csv("y = RGPDPC, X = EFW, LogDiffResults")
results_df

In [ ]:
# graph scatter of predictor and RGDP per capita (Predicted vs Observed)

fig, ax = plt.subplots(figsize = (20,12))
r_df.plot.scatter(x = y_var[0],
                 y = "Predictor",
                 s = 50,
                 alpha = .7,
                 ax = ax)

In [ ]:
# create residual plot functions below.


def plot_residuals(df, y_var, x_vars):
    fig, ax = plt.subplots(figsize = (14,10))
    df.plot.scatter(x = y_var[0],y = "Predictor", s = 30, ax = ax)
    plt.xticks(rotation=90)
    plt.show()
    plt.close()

    #cycle through all variables included in our variables
    # use a for loop and graph through
                   
    for var in y_var + x_vars:
        fig, ax = plt.subplots(figsize = (14,10))
        df.plot.scatter(x = var,
                     y = "Residuals", 
                      s = 30, ax = ax)
        ax.axhline(0, ls = "--", color = "k")
        plt.xticks(rotation=90)
        plt.show()
        plt.close()
plot_residuals(r_df, y_var, x_vars)

In [ ]:
# add one to every value so our cumulative products don't result in 0
cumulative_data = r_df[[y_var[0], "Predictor"]] + 1
cumulative_data

In [ ]:
# create plots of RGDP per capita and predictor value

for country in countries:
    try:
        plot_data = r_df.loc[country]
        fig, ax = plt.subplots(figsize = (12,10))
        plot_data[y_var + ["Predictor"]].add(1).cumprod().plot.line(ax = ax,
                                                           legend = True)
    except:
        print(country + "does not appear to be in index")
    ax.set_title(country)
    plt.plot()

In [ ]:
# recreate our regression except using a new capita lag.

r_df = reg_data.copy()
r_df["RGDP Per Capita Lag"] = reg_data[
    "RGDP Per Capita"].groupby("ISO_Code_3").shift(years_diff)
r_df = r_df.dropna(axis = 0, how = "any")
x_vars.append("RGDP Per Capita Lag")
y = r_df[y_var]
X = r_df[x_vars]
X["Constant"] = 1
results = sm.OLS(y, X).fit()
r_df["Predictor"] = results.predict()
results.summary()

In [ ]:
# plot residuals to see if assumptions met
r_df["Residuals"] = results.resid
fig, ax = plt.subplots(figsize = (12,8))
r_df[["Residuals"]].plot.hist(bins = 100, ax = ax)

In [ ]:
# plot residuals to see if there is a hidden bias
plot_residuals(r_df, y_var, x_vars)

In [ ]:
# clean data from previous regression
del r_df["Predictor"]
del r_df["Residuals"]
del r_df["RGDP Per Capita Lag"]
r_df

In [ ]:
# fix x_vars and y_var to be indicative of new variable choices
x_vars, y_var = list(r_df.keys()[2:7]), [r_df.keys()[7]]
r_df[y_var + x_vars]

In [ ]:
# take the difference of the variables over time

r_df = r_df[y_var + x_vars].groupby("ISO_Code_3").diff(years_diff)


In [ ]:
# dropna
r_df = r_df.dropna(axis = 0, how = "any")

In [ ]:
# regression output using new vars and predictor
y = r_df[y_var]
X = r_df[x_vars]
X["Constant"] = 1
results = sm.OLS(y, X).fit()
r_df["Predictor"] = results.predict()
results.summary()

In [ ]:

r_df["Residuals"] = results.resid
fig, ax = plt.subplots(figsize = (12,8))
r_df[["Residuals"]].plot.hist(bins = 100, ax = ax)

In [ ]:
plot_residuals(r_df, y_var, x_vars)